version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user-task-manager
      - POSTGRES_PASSWORD=pass-task-manager